### ISSUE TITLE
Server doesn't detects the .env file

### ISSUE THREAD

**Issue by heliocarbex** [barodeur/pocket-archive-all#2]
Dear,

when I started the server the following error is being shown:

npm WARN pocket-achive-all@0.0.0 No repository field.
./dev-server: line 4: source: .env: file not found

Obs: The file .env exists with the appropriated key.

**Comment by heliocarbex** [comment]
I ran a debugger into the code, and the following was shown:

npm install
    ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by heliocarbex** [comment]
Guys,

I saw that the problems occured because I didn't have ready environment to run the NodeJs. After I solved all the problems, the server is just listening. Do I have to perform some command?
